### ISSUE TITLE
Game State UI doesn't show destroyed/active cores

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-corewars#20]
At the moment it's not possible to tell what cores are active or have been destroyed. It'd be nice to have this on the HUD somewhere for quick and easy reference.

**Comment by kurozael** [comment]
You can hold Q to view the scoreboard but at the moment it doesn't seem to be eliminating teams or showing if a core is destroyed. I'll sort this, I think even showing a horizontal list of team colored circles on the UI and removing a circle when their core is destroyed would provide a quick reference.
