### ISSUE TITLE
CoreWars whitelist issue?

### ISSUE THREAD

**Issue by JustPlayerDE** [Facepunch/sbox-corewars#28]
I'm not able to start a CoreWars game and i also haven't touched the access whitelist and verified the game files or even completly reinstalled it :eyes:

i  attached a log file where i started the game (in non-dev) and only tried to start the CoreWars game with default setup, after that i closed the game.

[Log.log](https://github.com/Facepunch/sbox-corewars/files/9942279/Log.log)

**Comment by dd123-a** [comment]
where you get the game

**Comment by JustPlayerDE** [comment]
https://sbox.game/
