### ISSUE TITLE
some bugs and other things

### ISSUE THREAD

**Issue by CoolMasterChief** [Facepunch/sbox-corewars#8]
1. E is both the Interact key and the button to enter third/first person.

2. Hitting tab to enter the inventory can sometimes cause the inventory to bug out and repeatedly open and close

3. while spectating and entering another players base causes the game to lag and stutter like crazy

4. pick ups can block your path and you can become stuck on them

**Comment by kurozael** [comment]
Thanks @CoolMasterChief, I've moved these all into seperate issues.
